### ISSUE TITLE
validators version issue?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#692] opened 2024-06-19 14:15 UTC
https://github.com/oda-hub/dispatcher-app/blob/e4b778401cd190512bfd18c69ec4ec27863d2a51/requirements.txt#L39

this breaks in here

https://github.com/oda-hub/oda_api/actions/runs/9135072621/job/26304556424

Why could it be?

**Comment by burnout87** [comment] 2024-06-19 14:42
That happens because there is an attempt to installs the library `validators` at the latest version, with python 3.7, which is not.

We never saw on the dispatcher because we run out github workflows using python 3.8 and up, never 3.7.

Can we remove the support to that python version ?

**Comment by volodymyrss** [comment] 2024-06-19 14:55
there is now a problem with [bokeh](https://github.com/oda-hub/dispatcher-app/blob/e4b778401cd190512bfd18c69ec4ec27863d2a51/requirements.txt#L13) - numpy compatibility.
Can we safely upgrade bokeh or should we freeze numpy?

**Comment by burnout87** [comment] 2024-06-19 15:26
I quickly tried to install the latest versions of bokeh and numpy and I don't see that error, but of course it is not a guarantee

**Comment by volodymyrss** [comment] 2024-06-19 15:58
> I quickly tried to install the latest versions of bokeh and numpy and I don't see that error, but of course it is not a guarantee

If it works for the dispatcher visualization, if you tried that on your dev instance, lets upgrade. Could you check if it works on a dev instance?

**Comment by burnout87** [comment] 2024-06-19 15:58
no, I spoke a bit too early, and it seems there would be more problems upgrading `bokeh` https://github.com/oda-hub/dispatcher-app/actions/runs/9584813165/job/26429259309?pr=693

**Comment by volodymyrss** [comment] 2024-06-19 15:59
> no, I spoke a bit too early, and it seems there would be more problems upgrading `bokeh` https://github.com/oda-hub/dispatcher-app/actions/runs/9584813165/job/26429259309?pr=693

need to pick one that works I guess

**Comment by burnout87** [comment] 2024-06-20 10:32
it seems like that by freezing the numpy version the issue is solved:

```python
numpy==1.24.4
```

**Comment by burnout87** [comment] 2024-06-21 14:03
ok, it seems that https://github.com/oda-hub/dispatcher-app/pull/693 fixed it
I guess we can close this?

**Closed** 2024-06-21 14:04 UTC
