### ISSUE TITLE
send e-mail upon completion of request (https://staging.odahub.fr/mmoda/)

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-app#553] opened 2023-07-13 06:44 UTC
The frontend (or the dispatcher?) sends an e-mail upon submission of request, which is useful particularly for the Fermi/LAT service, where the requests can be long. However, the initial e-mail promises that I will get a new e-mail upon completion of the request. This second e-mail never comes..... Is this a bug (the behaviour observed at https://staging.odahub.fr/mmoda/)

**Comment by dsavchenko** [comment] 2023-07-13 14:34
I think I never got the completion emails when requesting nb2workflow products
What could be specific about this type of requests?

**Comment by dsavchenko** [comment] 2023-09-20 12:46
This issue persists for French staging. Do we have any updates/progress on it?

**Comment by burnout87** [comment] 2023-09-26 07:27
I kept noticing the same behavior

**Comment by volodymyrss** [comment] 2023-10-16 08:35
probably message queue piled up

**Comment by volodymyrss** [comment] 2023-10-16 08:35
this has to do with message passing on the nb2workflow backend

**Comment by dsavchenko** [comment] 2023-10-19 17:45
This issue was due to 
1. dispatcher config option `email_sending_timeout_default_threshold` was set to large number
2. https://github.com/oda-hub/oda_api/pull/220 

Therefore, I close this one, as it is specific to https://staging.odahub.fr/mmoda 

@burnout87 still notices email sending problems sometimes with other instances. Probably we need a separate issue then

**Closed by dsavchenko** 2023-10-19 17:45 UTC
Labels: bug

**Comment by volodymyrss** [comment] 2023-10-19 18:05
thanks for updating!

> This issue was due to
> 
>     1. dispatcher config option `email_sending_timeout_default_threshold` was set to large number
> 
>     2. [better url validation regex oda_api#220](https://github.com/oda-hub/oda_api/pull/220)
> 
> 
> Therefore, I close this one, as it is specific to https://staging.odahub.fr/mmoda
> 
> @burnout87 still notices email sending problems sometimes with other instances. Probably we need a separate issue then

Here we decided to use inspect endpoint to investigate the cause. @burnout87 please follow-up in another issue

**Comment by volodymyrss** [comment] 2023-10-19 18:36
I note, however, that at the moment, https://staging.odahub.fr/mmoda/ fails to process callback and does not nominally complete any nb workflow.  Since we use it for testing, it's important to have it live soon.

**Comment by dsavchenko** [comment] 2023-10-20 12:21
> I note, however, that at the moment, https://staging.odahub.fr/mmoda/ fails to process callback and does not nominally complete any nb workflow. Since we use it for testing, it's important to have it live soon.

I just tried, and it was successfully able to reach the 'ready' state. So this issue is resolved there. 

However, sometimes I notice the behavior when one of the POST requests which frontend sends to dispatcher ends up with 504: gateway timeout. In this case, there are no visible consequences, frontend just continues to show submitted state, but doesn't send any requests anymore. 
This could be improved both in frontend, but we also need to investigate, what causes these timeouts.
